# Generated by Django 2.1.7 on 2019-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('AV', 'Pagamento à vista'), ('P2', 'Parcelado em 2x'), ('P3', 'Parcelado em 3x'), ('P4', 'Parcelado em 4x')], default='AV', max_length=2),
        ),
    ]
